#!/bin/bash
# ~/.config/aios/flows/chat

# Streaming output via bat
bat_stream() {
	bat --color=always \
		--wrap=character \
		--unbuffered \
		--file-name "LlamaResponse.md" \
		--theme "TwoDark" \
		--tabs=4 \
		--style "numbers,grid,header-filename" \
		--paging=never \
		--pager "less --RAW-CONTROL-CHARS --quit-if-one-screen --mouse"

}

# Interact with CLI from Shell, Route output to bat
chat_with_llm() {
	local input="$1"
	llm <<<"$input" -c | bat_stream
}

# Read initial input
read -r input

# Process initial input
chat_with_llm "$input"

# Main chat loop for continuous interaction with the LLM
while true; do
	read -r input

	if [[ $input == "q" ]]; then
		break
	fi

	chat_with_llm "$input"
done
