#!/bin/zsh

deepseek_stream() {
    local max_tokens="${1:-1024}"

    curl -sN -L -X POST 'https://api.deepseek.com/beta/chat/completions' \
        -H 'Content-Type: application/json' \
        -H 'Accept: application/json' \
        -H "Authorization: Bearer ${DEEPSEEK_API_KEY}" \
        --data-raw "{
          \"messages\": [
            {
              \"content\": \"You are an expert frontend developer, specializing in TypeScript\",
              \"role\": \"system\"
            },
            {
              \"content\": \"Please provide a comprehensive, detailed explanation of TypeScript Generics. Please use many examples to demonstrate the practical and conceptual aspects of this pattern.\",
              \"role\": \"user\"
            }
          ],
          \"model\": \"deepseek-chat\",
          \"frequency_penalty\": 0,
          \"max_tokens\": ${max_tokens},
          \"presence_penalty\": 0,
          \"response_format\": {
            \"type\": \"text\"
          },
          \"stop\": null,
          \"stream\": true,
          \"stream_options\": null,
          \"temperature\": 1,
          \"top_p\": 1,
          \"tools\": null,
          \"tool_choice\": \"none\",
          \"logprobs\": false,
          \"top_logprops\": null
        }" \
		| sed -u '/^data: \[DONE\]/d; s/^data: //' \
		| jq -r -j --unbuffered '.choices[0].delta.content' \
		| highlight --out-format=xterm256 \
  			--syntax=markdown \
  			--style=base16/material-darker \
  			--force --stdout \
		| sed -u -E '/^```/,/^```/!s/\*\*//g; /^```/,/^```/!s/\*//g; /^```/,/^```/!s/####//g; /^```/,/^```/!s/###//g; /^```/,/^```/!s/##//g' \
		| awk '
    		{
    		    line = $0 "\n"  # Capture the full line including newline
    		    for(i=1; i<=length(line); i++) {
    		        printf "%s", substr(line,i,1)
    		        system("sleep 0.001")
    		        fflush()
    		    }
    		}'
}
deepseek_stream "$@"